BEGIN;

ALTER TABLE users
ADD COLUMN IF NOT EXISTS google_sub TEXT UNIQUE,
ADD COLUMN IF NOT EXISTS auth_provider TEXT NOT NULL DEFAULT 'password';

ALTER TABLE users
ALTER COLUMN password_hash DROP NOT NULL;

COMMIT;
